;QR100318, JOSUE QUINTEROS
name "PARCIAL2"   

ORG 100h

 ;SE INICIA EL ENTORNO GRAFICO, LLAMANDO A LA ETIQUETA
 CALL MOSTRARENTORNOGRAFICO
 
 ; SE MUESTRA EL MENSAJE INCICIAL CON LAS OPCIONES DISPONIBLES DEL PROGRAMA
 LEA DX,MSGINICIO
 CALL IMPRIMIR
 
 ; SE LLAMA ESTA ETIQUETA QUE CAPTURA UN NUMERO QUE SE GUARDA EN AL, CUYO VALOR SE USARA PARA LA ESTRUCTURA SWITCH
 CALL OBTENEROPCIONELEGIDA
 
 ;ESTRUCTURA SWITCH PARA PROCESAR OPCIONES
 CMP AL, 1
 JZ MOSTRARNOMBRE
    
 CMP AL, 2
 JZ SUMAR
    
 CMP AL,3 
 JZ RESTAR
    
 CMP AL,4 
 JZ MULTI
    
 CMP AL,5 
 JZ DIVIDIR
    
 CMP AL,6 
 JZ SALIR
    
 ;NO SE ENCONTRO NINGUNA OPCION SE DESPIDE CON UN MENSAJE ADECUADO     
 JNZ MOSTRARMSGINVALIDO
 JMP SALIR
                                  
 
 ; LAS SIGUIENTES ETIQUETAS SON LLAMADAS O USADAS DESDE EL SWITCH O AL INICIO DEL PROGRAMA
 ; NO SERAN PARTE DE LA EJECUCION NORMAL DEL PROGRAMA, AUNQUE ELLAS FINALIZAN LA EJECUCION DEL PROGRAMA


;ACA SE LEE UN NUMERO DEL ENTORNO GRAFICO, CONVIRTIENDO EL NUMERO DE SU CODIGO ASCII A DECIMAL Y SE GUARDA EN AL 
CAPTURARNUMERO:
    MOV AH,01
    INT 21H
    SUB AL, 30H
    RET
;ESTA ETIQUETA SE DEFINE SOLO PARA FINES DE LEGIBILIDAD DEL CODIGO   
OBTENEROPCIONELEGIDA:
    CALL CAPTURARNUMERO 
    RET
;ACA SE MUESTRA UN MENSAJE EN EL ENTORNO GRAFICO Y SE OBTIENE EL PRIMER OPERANDO    
OBTENERPRIMEROPERANDO:
    LEA DX, MSGOBTENERPRIMERNUM
    CALL IMPRIMIR
    CALL CAPTURARNUMERO 
    RET

;SE ENVIA EL VALOR DE AL A CL POR UN MOMENTO PORQUE AL TIENE EL PRIMER NUMERO, Y ESE SE ENVIA A CL, PARA GUARDARLO Y LUEGO RECIBIR EL SEGUNDO
; EL CUAL SE ASIGNA  A BL, Y FINALMENTE SE DEVUELVE EL VALOR CL A AL, ASI PODER HACER OPERACIONES ENTRE AL Y BL     
OBTENERSEGUNDOPERANDO:
    LEA DX, MSGOBTENERSEGUNDONUM
    MOV CL, AL
    CALL IMPRIMIR 
    CALL CAPTURARNUMERO 
    MOV BL, AL 
    MOV AL, CL  
    RET

; ESTAS ETIQUETA SE LLAMAN DESDE EL SWITCH, SE ENCARGA DE OBTENER LOS DOS NUMEROS, EL RESULTADO LO GUARDA EN AL Y LLAMA LA ETIQUETA ASIGNADA PARA IMPRIMIR NUMEROS, Y FINALMENTE TERMINAN EL PROGRAMA 
SUMAR:
    CALL OBTENERPRIMEROPERANDO 
    CALL OBTENERSEGUNDOPERANDO
    ADD AL, BL
    MOV DL, AL
    CALL IMPIRIMIRRESULTADO
    JMP SALIR
    
RESTAR:
    CALL OBTENERPRIMEROPERANDO 
    CALL OBTENERSEGUNDOPERANDO
    SUB AL, BL
    MOV DL, AL
    CALL IMPIRIMIRRESULTADO
    JMP SALIR
MULTI: 
    CALL OBTENERPRIMEROPERANDO 
    CALL OBTENERSEGUNDOPERANDO
    MUL BL
    MOV DL, AL
    CALL IMPIRIMIRRESULTADO
    JMP SALIR
    
DIVIDIR:
    CALL OBTENERPRIMEROPERANDO 
    CALL OBTENERSEGUNDOPERANDO
    MOV AH, 0
    DIV BL
    MOV DL, AL
    CALL IMPIRIMIRRESULTADO
    JMP SALIR 
MOSTRARNOMBRE:
    LEA DX,NOMBRE
    CALL IMPRIMIR
    JMP SALIR    
MOSTRARMSGINVALIDO:
    LEA DX,OPCIONINVALIDAMSG
    CALL IMPRIMIR
    JMP SALIR
SALIR:
    RET 
 


;INICIA EL ENTORNO GRAFICO               
MOSTRARENTORNOGRAFICO:
    MOV AX,0003h  
    INT 10h       
    

    MOV AX, 1003h 
    MOV BX, 0
    INT 10h
    RET
    
  
;IMPRIME EL VALOR DE DX          
IMPRIMIR:
    MOV AH,09h 
    INT 21h    
    RET
    
 
;IMPRIME EL VALOR DE DL, SOLO ES USADO EN OPERACIONES ARITMETICAS
IMPIRIMIRRESULTADO: 
    ADD DL, 30h
    MOV CL, DL
    LEA DX, RESULTADOMSG
    CALL IMPRIMIR 
    MOV DL,CL
    MOV AH,2 
    INT 21H
    RET
    
    
;VARIABLES                                                       
NOMBRE DB 13,10,"MI NOMBRE ES JOSUE QUINTEROS Y MI CARNET QR100318","$"
OPCIONINVALIDAMSG DB 13,10,"OPCION INVALIDA, ASEGURESE DE SELECCIONAR UNA ACCION CORRECTA","$"
MSGINICIO DB "SELECCIONE UNA OPCION DEL 1 AL 6",13,10,13,10,"1-MOSTRAR NOMBRE",13,10,"2-SUMAR",13,10,"3-RESTAR",13,10,"4-MULTIPLICAR",13,10,"5-DIVIDIR",13,10,"6-SALIR",13,10,"$" 
MSGOBTENERPRIMERNUM DB 13,10,"INGRESE EL PRIMER NUMERO A OPERAR ","$"
MSGOBTENERSEGUNDONUM DB 13,10,"INGRESE EL SEGUNDO NUMERO A OPERAR ","$"
RESULTADOMSG DB 13,10,13,10,"EL RESULTADO DE SU OPERACION ES: ","$" 
    
   