;QR100318, JOSUE QUINTEROS
name "LAB2"   

ORG 100h

;SIMULACION DE SWITCH CASE EN ASSEMBLER
 
;DECLARACION DE USOS DE REGISTROS PARA RESOLVER EL PROBLEMA
;AX OBTENDRA EL OPERADOR 1 
;BX OBTENDRA EL OPERADOR 2
;CX SERA EN ESTE CASO LA OPCION QUE SE DESEA REALIZAR => CX SIMULARA LA VARIABLE QUE SE PASA A UN SWITCH 
;STATEMENT EN UN LENGUAJE DE ALTO NIVEL
;EN EL CASO DE SUMA,RESTA,MULTIPLICACION Y DIVISION EL REGISTRO DX GUARDARA AL FINAL DEL PROGRAMA EL RESULTADO DE LA OPERACION ELEGIDA
;EN EL CASO DE MOSTRAR NOMBRE DEL ESTUDIANTE ESTE SE GUARDARA EN UNA VARIABLE AL IGUAL QUE LA OPCION DE DEFAULT
;ESTO ES UTIL A FIN DE TESTEAR EL FUNCIONAMIENTO DEL PROGRAMA 

;DECLARACION DE NUMERO DE CASOS 
;                               CASO OPCION 1: REALIZA LA SUMA
;                               CASO OPCION 2: REALIZA LA RESTA
;                               CASO OPCION 3: REALIZA LA MULTIPLICACION
;                               CASO OPCION 4: REALIZA LA DIVISION
;                               CASO OPCION 5: MUESTRA EL NOMBRE DEL ESTUDIANTE (USO DE ENTORNO GRAFICO)
;                               CASO OPCION DEFAULT: MUESTRA MENSAJE DE OPCION INVALIDA (DEFAULT = NO ELIGIO NINGUNA OPCION DISPOBIBLE)(USO DE ENTORNO GRAFICO)
                             
;ESTE PROGRAMA CREA EL ENTORNO CASO SOLO SI SERA UTILIZADO

MOV AX,10 ; OPERANDO 1 
MOV BX,10 ; OPERANDO 2

MOV CX,66  ; OPCION 
         
;COMPARA CX CON 1 PARA VERIFICAR DESPUES SI FUE ESTA LA OPCION ELEGIDA Y SE VERIFICA CON LA BANDERA JZ PARA LLAMAR A LA FUNCION ELEGIDA        
CMP CX,1
JZ SUMAR
 
;COMPARA CX CON 2 PARA VERIFICAR DESPUES SI FUE ESTA LA OPCION ELEGIDA Y SE VERIFICA CON LA BANDERA JZ PARA LLAMAR A LA FUNCION ELEGIDA
CMP CX,2
JZ RESTAR

;COMPARA CX CON 3 PARA VERIFICAR DESPUES SI FUE ESTA LA OPCION ELEGIDA Y SE VERIFICA CON LA BANDERA JZ PARA LLAMAR A LA FUNCION ELEGIDA
CMP CX,3
JZ MULTI

;COMPARA CX CON 4 PARA VERIFICAR DESPUES SI FUE ESTA LA OPCION ELEGIDA Y SE VERIFICA CON LA BANDERA JZ PARA LLAMAR A LA FUNCION ELEGIDA
CMP CX,4
JZ DIVIDIR

;COMPARA CX CON 5 PARA VERIFICAR DESPUES SI FUE ESTA LA OPCION ELEGIDA Y SE VERIFICA CON LA BANDERA JZ PARA LLAMAR A LA FUNCION ELEGIDA
CMP CX,5
JZ MOSTRARNOMBRE

;SI LA ULTIMA COMPARACION NO FUE IGUAL ES PORQUE NINGUNA OPCION COMPARADA ANTERIORMENTE A SIDO SELECCIONADA (DEFAULT)
JNZ MOSTRARMSGINVALIDO 


;FUNCIONES QUE LLAMAN LAS BANDERAS AL ENCONTRAR LA OPCION ELEGIDA, CABE DESTACAR QUE ESTAS FUNCIONES SALTAN A SALIR PARA TERMINAR EL PROGRAMA
;Y EVITAR QUE SE EJECUTEN OTRAS FUNCIONES
SUMAR:
    ADD AX, BX
    MOV DX, AX
    JMP SALIR
    
RESTAR:
    SUB AX, BX
    MOV DX, AX
    JMP SALIR
MULTI:
    MUL BX
    MOV DX, AX
    JMP SALIR
DIVIDIR:
    DIV BX
    MOV DX, AX
    JMP SALIR
MOSTRARNOMBRE:
    CALL MOSTRARENTORNOGRAFICO
    LEA DX, NOMBRE
    CALL IMPRIMIR
    JMP SALIR
MOSTRARMSGINVALIDO:
    CALL MOSTRARENTORNOGRAFICO
    LEA DX,OPCIONINVALIDAMSG
    CALL IMPRIMIR
    JMP SALIR     

    
    
;VARIABLES QUE CONTIENEN EL MENSAJE A MOSTRAR PARA LA OPCION 5 Y 6 RESPECTIVAMENTE     
NOMBRE DB "MI NOMBRE ES JOSUE QUINTEROS$"
OPCIONINVALIDAMSG DB "OPCION INVALIDA, ASEGURESE DE SELECCIONAR UNA ACCION CORRECTA$"
    
            

;Estableciendo entorno de pantalla grafica solo si la opcion elegida lo requiere se llama la etiqueta (OPCION 5 Y 6)
MOSTRARENTORNOGRAFICO:
            MOV AX,0003h  
            INT 10h       
    

            MOV AX, 1003h 
            MOV BX, 0
            INT 10h
            RET


SALIR:
    RET 
    
  
;IMPRIME EL VALOR DE DX          
IMPRIMIR: 
    MOV AH,09h 
    INT 21h    
    RET 
        